spring.application.name=inventory-servic

logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_inventario_monolito
spring.datasource.username=postgres
spring.datasource.password=jeff0831
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Nivel de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Nivel raíz
logging.level.root=INFO

# Tu paquete - verás tus propios logs y excepciones
logging.level.com.inventory.inventory_servic=DEBUG

# Spring MVC - solo lo suficiente para ver qué excepción se lanzó
logging.level.org.springframework.web.servlet.mvc.method.annotation=WARN
logging.level.org.springframework.web.servlet.DispatcherServlet=WARN

spring.mvc.log-resolved-exception=true

